"""Figure dispatcher: ``plot.py <task> [--fig NAME] [--run NAME]``.

Thin glue — loads the saved data for a task from ``results/runs/`` and calls
the relevant ``attention.plotting`` function(s), writing PNGs to
``results/figures/<task>-<name>.png``.  No plotting math lives here.  If a
task has no data yet, it warns cleanly and exits without error.

``fig-a`` is a no-op placeholder (Task A has no training or data to plot;
the first real figure is Task B's training curve).  Timing/memory axes are
machine-relative (a ratio to a baseline the demo measured on this machine),
never absolute seconds.

Provided — students run this; they do not edit it.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any, Callable

import numpy as np

from attention.plotting.bars import grouped_bars
from attention.plotting.curves import line_grid, line_plot
from attention.plotting.heatmap import attention_heatmap, diagonal_overlay
from attention.plotting.maps import heatmap_grid
from attention.plotting.scoreboard import scoreboard_heatmap
from attention.plotting.style import relative_to_baseline
from attention.vocab import N_CONTENT

_RESULTS = Path(__file__).resolve().parents[1] / "results"
_FIGURES = _RESULTS / "figures"

# Every battery run whose scoreboard.json feeds the cumulative heatmap
# (rows accumulate as later tasks land their demos).
_BATTERY_TAGS = [
    ("rnn", "RNN"),
    ("rnn-attn", "RNN+bahdanau"),
    ("self-attn", "self-attention"),
    ("multihead", "multi-head"),
    ("transformer", "decoder-only"),
    ("sort-gap", "encoder-decoder"),
]

# One builder per figure: returns True if it plotted, False if its data is
# not on disk yet.
_Builders = list[tuple[str, Callable[[], bool]]]


def _resolve(pinned: str | None, tag: str) -> Path | None:
    """The run directory for *tag* (or the ``--run``-pinned one)."""
    if pinned is not None:
        path = Path(pinned)
        if not path.is_absolute():
            path = _RESULTS / "runs" / pinned
        return path if path.is_dir() else None
    from attention.run import latest_run

    return latest_run(_RESULTS, tag)


def _load(run_dir: Path | None, name: str) -> Any:
    if run_dir is None:
        return None
    path = run_dir / name
    if not path.exists():
        return None
    with open(path) as fh:
        return json.load(fh)


def _out(task: str, name: str) -> str:
    return str(_FIGURES / f"{task}-{name}.png")


def _accuracies(scoreboard: dict[str, Any]) -> dict[str, float]:
    return {task: row["accuracy"] for task, row in scoreboard["rows"].items()}


def _cumulative_scoreboard() -> Callable[[], bool]:
    """Heatmap over every battery scoreboard produced so far.

    Task-independent — always written to ``battery.png`` (the figure spans
    every mechanism, not one task), regenerated by ``fig-battery`` whenever a
    battery-contributing task's demo runs.
    """

    def build() -> bool:
        boards: dict[str, dict[str, float]] = {}
        for tag, label in _BATTERY_TAGS:
            sb = _load(_resolve(None, tag), "scoreboard.json")
            if sb is not None:
                boards[label] = _accuracies(sb)
        if not boards:
            return False
        scoreboard_heatmap(boards, title="Battery scoreboard (token accuracy)", out=str(_FIGURES / "battery.png"))
        return True

    return build


# ---------------------------------------------------------------------------
# Per-task figure builders
# ---------------------------------------------------------------------------


def _figs_b(pinned: str | None) -> _Builders:
    run = _resolve(pinned, "rnn")

    def training_curve() -> bool:
        metrics = _load(run, "metrics.json")
        if metrics is None:
            return False
        series = {task: (h["steps"], h["train_loss"]) for task, h in metrics.items()}
        line_plot(
            series,
            title="RNN training loss across the battery",
            xlabel="step",
            ylabel="masked cross-entropy",
            out=_out("b", "training-curve"),
        )
        return True

    return [("training-curve", training_curve)]


def _figs_c(pinned: str | None) -> _Builders:
    run = _resolve(pinned, "bahdanau")

    def recall() -> bool:
        data = _load(run, "recall_vs_distance.json")
        if data is None:
            return False
        xs = data["needle_distance"]
        series = {label: (xs, data[label]) for label in ("rnn", "rnn_bahdanau") if label in data}
        line_plot(
            series,
            title="Associative recall vs needle distance",
            xlabel="needle distance (pairs before the query)",
            ylabel="token accuracy",
            out=_out("c", "recall-vs-distance"),
        )
        return True

    def grad_norm() -> bool:
        data = _load(run, "gradient_probe.json")
        if data is None:
            return False
        line_plot(
            {"decoder loss → source embedding": (data["source_position"], data["grad_norm"])},
            title="Gradient norm reaching each source position",
            xlabel="source position",
            ylabel="grad norm (log)",
            out=_out("c", "grad-norm"),
            logy=True,
        )
        return True

    def serial_timing() -> bool:
        data = _load(run, "serial_timing.json")
        if data is None:
            return False
        times = data["forward_seconds"]
        line_plot(
            {"RNN+attention forward": (data["length"], relative_to_baseline(times, times[0]))},
            title="Inference wall-clock vs sequence length",
            xlabel="sequence length",
            ylabel="time (× shortest length; machine-relative)",
            out=_out("c", "serial-timing"),
        )
        return True

    return [
        ("recall-vs-distance", recall),
        ("grad-norm", grad_norm),
        ("serial-timing", serial_timing),
    ]


def _figs_d(pinned: str | None) -> _Builders:
    scaling_run = _resolve(pinned, "scaling")
    equiv_run = _resolve(pinned, "equivariance")

    def _scaling_metric(metric: str, ylabel: str, *, logy: bool) -> bool:
        data = _load(scaling_run, "scaling_ablation.json")
        if data is None:
            return False
        xs = data["d_k"]
        series = {arm: (xs, data[f"{metric}_{arm}"]) for arm in ("scaled", "unscaled")}
        line_plot(
            series,
            title=f"Scaling ablation — {ylabel} vs d_k",
            xlabel="key dimension d_k",
            ylabel=ylabel,
            out=_out("d", metric.replace("_", "-")),
            logx=True,
            logy=logy,
        )
        return True

    def equivariance() -> bool:
        data = _load(equiv_run, "permutation_equivariance.json")
        if data is None or "position_free_accuracy" not in data:
            return False
        groups = {task: {"position-free single layer": acc} for task, acc in data["position_free_accuracy"].items()}
        grouped_bars(
            groups,
            title=f"Order tasks without positions (equivariance gap {data['equivariance_gap']:.1e})",
            ylabel="token accuracy",
            out=_out("d", "permutation-equivariance"),
        )
        return True

    return [
        ("logit-var", lambda: _scaling_metric("logit_var", "pre-softmax logit variance", logy=True)),
        ("softmax-max", lambda: _scaling_metric("softmax_max", "softmax max probability", logy=False)),
        ("grad-norm", lambda: _scaling_metric("grad_norm", "query grad norm", logy=True)),
        ("permutation-equivariance", equivariance),
    ]


def _figs_e(pinned: str | None) -> _Builders:
    run = _resolve(pinned, "two-relation")

    def accuracy() -> bool:
        data = _load(run, "two_relation.json")
        if data is None:
            return False
        groups = {label: {"two-relation accuracy": acc} for label, acc in data["accuracy"].items()}
        grouped_bars(
            groups,
            title="Two-relation task: single vs multi-head",
            ylabel="token accuracy",
            out=_out("e", "two-relation"),
        )
        return True

    def entropy() -> bool:
        data = _load(run, "two_relation.json")
        if data is None or not data.get("per_head_entropy"):
            return False
        groups = {label: {f"head {i}": e for i, e in enumerate(entropies)} for label, entropies in data["per_head_entropy"].items()}
        grouped_bars(
            groups,
            title="Per-head attention entropy (trained)",
            ylabel="entropy (nats)",
            out=_out("e", "head-entropy"),
        )
        return True

    def decomposition() -> bool:
        """The average hides it: two relations are free, one carries the story."""
        data = _load(run, "two_relation.json")
        if data is None or "sweep" not in data:
            return False
        sweep = data["sweep"]
        xs = sweep["num_heads"]
        # EOS is 1.000 everywhere and would be drawn exactly on top of relation
        # A, hiding it.  It is named in the title instead of plotted.
        keys = [k for k in sorted(sweep["per_seed"][f"heads_{xs[0]}"]) if k != "EOS"]
        series: dict[str, Any] = {}
        bands: dict[str, Any] = {}
        for key in keys:
            runs = [sweep["per_seed"][f"heads_{h}"][key] for h in xs]
            series[key] = (xs, [sum(r) / len(r) for r in runs])
            bands[key] = ([min(r) for r in runs], [max(r) for r in runs])
        line_plot(
            series,
            title=f"Two-relation task, per output position ({sweep['seeds']} seeds; band = min–max)\nthe third position, EOS, is 1.000 everywhere",
            xlabel="number of heads",
            ylabel="token accuracy",
            out=_out("e", "relation-decomposition"),
            bands=bands,
            hlines=[(data["chance"], "chance"), (data["value_set_prior"], "value-set prior")],
            logx=True,
            xticks=xs,
        )
        return True

    def head_attention() -> bool:
        """What each head attends to at the two output queries."""
        data = _load(run, "two_relation.json")
        if data is None or not data.get("head_attention"):
            return False
        h = data["head_attention"]
        rows = np.array(h["rows"])  # [H, 2, L]
        correct = h["correct_columns"]
        overlay = [(0, correct[0]), (1, correct[1])]
        heatmap_grid(
            [(f"head {i}", rows[i]) for i in range(rows.shape[0])],
            title="Where each head looks at the two output queries",
            xlabel="key position (role: sampled token)",
            cbar_label="attention weight",
            out=_out("e", "head-attention"),
            xticklabels=h.get("key_labels", h["tokens"]),
            yticklabels=h["query_labels"],
            overlays=[overlay] * rows.shape[0],
            overlay_label="correct source",
            ncols=2,
            xtick_rotation=45,
            ytick_rotation=45,
        )
        return True

    return [
        ("two-relation", accuracy),
        ("head-entropy", entropy),
        ("relation-decomposition", decomposition),
        ("head-attention", head_attention),
    ]


def _figs_f(pinned: str | None) -> _Builders:
    run = _resolve(pinned, "lengthgen")

    def length_gen() -> bool:
        data = _load(run, "length_generalization.json")
        if data is None:
            return False
        xs = data["eval_length"]
        series = {scheme: (xs, accs) for scheme, accs in data.items() if scheme != "eval_length"}
        line_plot(
            series,
            title="Copy accuracy vs eval length (trained at n ≤ 32)",
            xlabel="eval length",
            ylabel="token accuracy",
            out=_out("f", "length-generalization"),
            logx=True,
        )
        return True

    def locality() -> bool:
        data = _load(run, "alibi_locality.json")
        if data is None:
            return False
        xs = data["distance"]
        series = {scheme: (xs, data[scheme]) for scheme in ("sinusoidal", "alibi") if scheme in data}
        line_plot(
            series,
            title="ALiBi's locality prior: attention weight vs distance",
            xlabel="query–key distance |i − j|",
            ylabel="mean attention weight",
            out=_out("f", "alibi-locality"),
        )
        return True

    return [("length-generalization", length_gen), ("alibi-locality", locality)]


def _figs_g(pinned: str | None) -> _Builders:
    def _heads(mask_ok: bool, name: str, state_label: str) -> Callable[[], bool]:
        """Every head of the leaky / correct model, no head cherry-picked.

        Replaces the old last-layer head-mean map: averaging over heads smears
        a sharp single-head leak into a faint haze.  The grid shows all heads so
        the reader finds the peeking ones themselves, and needs both a buggy and
        a fixed run on disk to draw both states.
        """

        def build() -> bool:
            by_state = _runs_by_state(pinned, "transformer")
            if mask_ok not in by_state or "head_maps" not in by_state[mask_ok]:
                return False
            _head_grid(by_state[mask_ok], state_label, _out("g", name))
            return True

        return build

    def by_position() -> bool:
        """The leak's cost per token — buggy vs fixed, side by side.

        One panel per mask state, on a shared y-axis: under the bug the
        free-running curve falls away from teacher-forced; once fixed the two
        rejoin near the top.  Needs a buggy and a fixed run on disk for both
        panels (a single run draws its one panel).
        """
        by_state = _runs_by_state(pinned, "transformer")
        panels, n = [], None
        for mask_ok, panel_title in [(False, "mask still buggy (leaky)"), (True, "mask fixed (correct)")]:
            data = by_state.get(mask_ok)
            if data is None or "by_position" not in data:
                continue
            p = data["by_position"]
            n = data["by_position_length"]
            panels.append((panel_title, {label: (p["position"], p[label]) for label in ("teacher_forced", "free_running")}))
        if not panels:
            return False
        line_grid(
            panels,
            title=f"Accuracy at each generated token (copy, n={n})",
            xlabel="output token index",
            ylabel="token accuracy",
            out=_out("g", "accuracy-by-position"),
            hline=1.0 / N_CONTENT,
            hline_label="chance",
            ncols=2,
            marker="o",
            xinteger=True,
            label_refs_each=True,
        )
        return True

    return [
        ("heads-leaky", _heads(False, "heads-leaky", "leaky")),
        ("heads-correct", _heads(True, "heads-correct", "correct")),
        ("accuracy-by-position", by_position),
    ]


def _figs_h(pinned: str | None) -> _Builders:
    run = _resolve(pinned, "sort-gap")

    def alignment() -> bool:
        """Both architectures learn the same argsort: self-attention vs cross-attention."""
        data = _load(run, "sort_gap.json")
        if data is None or "decoder_only_alignment" not in data:
            return False
        dec_peak, enc_peak = data["decoder_only_peakiness"], data["encoder_decoder_peakiness"]
        panels = {
            f"decoder-only: self-attention\n(output → source, peakiness {dec_peak:.2f})": np.array(data["decoder_only_alignment"]),
            f"encoder-decoder: cross-attention\n(decoder → memory, peakiness {enc_peak:.2f})": np.array(data["encoder_decoder_alignment"]),
        }
        # Both models see the same example, so one argsort overlays both panels.
        overlay = list(enumerate(data["encoder_decoder_argsort"]))
        attention_heatmap(
            panels,
            title=f"Both architectures learn the same argsort alignment (Sort, n={data['n']})",
            xlabel="source position",
            ylabel="output step",
            out=_out("h", "alignment"),
            xticklabels=data["encoder_decoder_source"],
            yticklabels=[f"y{i + 1}" for i in range(data["n"])],
            overlay=overlay,
            overlay_label="argsort target",
        )
        return True

    def cross_attention_alignment() -> bool:
        """Cross-attention *is* the alignment: diagonal, anti-diagonal, argsort."""
        data = _load(run, "sort_gap.json")
        if data is None or "alignment" not in data:
            return False
        tasks = [t for t in ("copy", "reverse", "sort") if t in data["alignment"]]
        panels, overlays = [], []
        for task in tasks:
            a = data["alignment"][task]
            panels.append((f"{task} — argmax hits {a['alignment_accuracy']:.0%}", np.array(a["matrix"])))
            overlays.append([(row, col) for row, col in enumerate(a["true_alignment"])])
        first = data["alignment"][tasks[0]]
        heatmap_grid(
            panels,
            title="Cross-attention: where each output token reads from the source",
            xlabel="source position (encoder memory)",
            ylabel="output position (decoder query)",
            cbar_label="cross-attention weight",
            out=_out("h", "cross-attention-alignment"),
            xticklabels=first["source_tokens"],
            overlays=overlays,
            overlay_label="true alignment",
            gamma=0.5,
        )
        return True

    def source_dependency() -> bool:
        """Provable, training-free: a causal stack has exact zeros; an encoder does not."""
        data = _load(run, "sort_gap.json")
        if data is None or "source_dependency" not in data:
            return False
        # Log scale: the point is *which* entries are exactly zero (structurally
        # unreachable), not the magnitude of the ones that aren't.  On a linear
        # scale the diagonal swamps everything and both panels look identical.
        floor = 1e-6
        panels = {label: np.log10(np.array(m) + floor) for label, m in data["source_dependency"].items()}
        attention_heatmap(
            panels,
            title="Which source positions each source representation can see (untrained)",
            xlabel="source position changed",
            ylabel="source representation",
            out=_out("h", "source-dependency"),
            cmap="cividis",
            vmin=np.log10(floor),
            cbar_label="log₁₀ ‖Δ representation‖  (floor = no dependence)",
        )
        return True

    return [
        ("alignment", alignment),
        ("cross-attention-alignment", cross_attention_alignment),
        ("source-dependency", source_dependency),
    ]


def _figs_i(pinned: str | None) -> _Builders:
    run = _resolve(pinned, "linear")

    def cost() -> bool:
        data = _load(run, "linear_benchmark.json")
        if data is None or "cost" not in data:
            return False
        c = data["cost"]
        baseline = c["softmax_seconds"][0]
        series = {
            "softmax": (c["length"], relative_to_baseline(c["softmax_seconds"], baseline)),
            "linear": (c["length"], relative_to_baseline(c["linear_seconds"], baseline)),
        }
        line_plot(
            series,
            title="Forward cost vs sequence length",
            xlabel="sequence length",
            ylabel="time (× softmax @ shortest; machine-relative)",
            out=_out("i", "cost-vs-length"),
            logx=True,
            logy=True,
        )
        return True

    def recall() -> bool:
        data = _load(run, "linear_benchmark.json")
        if data is None or "recall" not in data:
            return False
        r = data["recall"]
        series = {label: (r["num_pairs"], r[label]) for label in ("softmax", "linear") if label in r}
        line_plot(
            series,
            title="Associative recall vs stored pairs",
            xlabel="stored pairs",
            ylabel="token accuracy",
            out=_out("i", "recall-vs-load"),
        )
        return True

    def snr() -> bool:
        data = _load(run, "linear_benchmark.json")
        if data is None or "snr" not in data:
            return False
        s = data["snr"]
        line_plot(
            {"linear-state retrieval": (s["num_pairs"], s["snr"])},
            title="Retrieval SNR vs stored pairs (training-free)",
            xlabel="stored pairs",
            ylabel="signal-to-noise ratio",
            out=_out("i", "snr"),
            logy=True,
        )
        return True

    return [("cost-vs-length", cost), ("recall-vs-load", recall), ("snr", snr)]


# ---------------------------------------------------------------------------
# All-heads grids for Task G — every self-attention head of the trained model,
# read from the "transformer" run tag and keyed by mask state so a leaky and a
# correct run draw as separate grids (leaky-vs-correct, observe before fix).
# ---------------------------------------------------------------------------


def _runs_by_state(pinned: str | None, tag: str) -> dict[bool, Any]:
    """Runs of *tag* keyed by causal-mask state, newest of each state winning.

    Run the demo before fixing the mask and again after, so both a leaky and a
    correct run are on disk; each becomes its own all-heads grid.
    """
    from attention.run import all_runs

    dirs = [_resolve(pinned, tag)] if pinned else all_runs(_RESULTS, tag)
    by_state: dict[bool, Any] = {}
    for run_dir in dirs:
        data = _load(run_dir, "train_transformer.json")
        if data is not None and "mask_ok" in data:
            by_state[bool(data["mask_ok"])] = data
    return by_state


def _head_grid(data: Any, state_label: str, out: str) -> None:
    """Draw every (layer, head) self-attention map of one run as a grid.

    No head is selected — that is the point.  The reader scans all of them and
    sees for themselves that most heads are diffuse and only a few read the next
    token; selecting the max-future-mass head would be circular (sorting on the
    quantity the figure claims to reveal).  Each panel is titled with its own
    future-attention-mass, and the square marks ``key = query + 1``.
    """
    entries = data["head_maps"]
    tokens = data["tokens"]
    panels = [(f"L{h['layer']} H{h['head']} · future {h['future_mass']:.0%}", np.array(h["map"])) for h in entries]
    overlays = [diagonal_overlay(len(tokens), 1) for _ in entries]
    heatmap_grid(
        panels,
        title=f"Every head of the {state_label} decoder-only transformer (Copy n=8)\n"
        "most heads are diffuse; the leak, when present, lives in a few — no head is cherry-picked",
        xlabel="key position (attended to)",
        ylabel="query position",
        out=out,
        cmap="magma",
        ncols=data.get("num_heads", 4),
        overlays=overlays,
        overlay_label="key = query + 1 (the next token)",
        xticklabels=tokens,
        yticklabels=tokens,
        gamma=2.0,
    )


_TASK_FIGS: dict[str, Callable[[str | None], _Builders]] = {
    "b": _figs_b,
    "c": _figs_c,
    "d": _figs_d,
    "e": _figs_e,
    "f": _figs_f,
    "g": _figs_g,
    "h": _figs_h,
    "i": _figs_i,
}


def plot_task(task: str, fig: str | None, run: str | None) -> None:
    if task == "a":
        print("Task A has no figure (no training or data to plot). The first real figure is Task B's training curve.")
        return
    if task == "battery":
        if _cumulative_scoreboard()():
            print(f"wrote {_FIGURES / 'battery.png'}")
        else:
            print("no battery scoreboards on disk yet — run a battery task's demo first.")
        return
    if task not in _TASK_FIGS:
        raise SystemExit(f"unknown task {task!r} (expected a-i)")
    builders = _TASK_FIGS[task](run)
    names = [name for name, _ in builders]
    if fig is not None and fig not in names:
        raise SystemExit(f"unknown figure {fig!r} for task {task!r} (expected one of {names})")
    for name, build in builders:
        if fig is not None and fig != name:
            continue
        if build():
            print(f"wrote {_out(task, name)}")
        else:
            print(f"no data for figure {name!r} — run `make demo-{task}` first.")


def main() -> None:
    parser = argparse.ArgumentParser(description="A6 figure dispatcher")
    parser.add_argument("task", help="task letter (a-i)")
    parser.add_argument("--fig", default=None, help="render one named figure")
    parser.add_argument("--run", default=None, help="pin a specific run dir")
    args = parser.parse_args()
    _FIGURES.mkdir(parents=True, exist_ok=True)
    plot_task(args.task, args.fig, args.run)


if __name__ == "__main__":
    main()
